[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:flask]
command=python3 /opt/fwui/app.py
directory=/opt/fwui
autostart=true
autorestart=true
stdout_logfile=/var/log/flask/flask-stdout.log
stderr_logfile=/var/log/flask/flask-stderr.log

[program:suricata]
command=/usr/bin/suricata -i eth2 -c /etc/suricata/suricata.yaml
autostart=true
autorestart=true
stdout_logfile=/var/log/suricata/suricata-stdout.log
stderr_logfile=/var/log/suricata/suricata-stderr.log

[program:ulogd2]
command=/usr/sbin/ulogd -c /etc/ulogd.conf
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:dnsmasq]
command=/usr/sbin/dnsmasq --no-daemon --conf-file=/etc/dnsmasq.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/dnsmasq/dnsmasq-stdout.log
stderr_logfile=/var/log/dnsmasq/dnsmasq-stderr.log

[program:arpmon]
command=python3 /opt/fwui/arpmon.py
autostart=true
autorestart=true
stdout_logfile=/var/log/arpmon/arpmon-stdout.log
stderr_logfile=/var/log/arpmon/arpmon-stderr.log
